title: brooks-anderson
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://brooks-anderson.github.io # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: brooks-anderson

# Build settings
#remote_theme: chrisrhymes/bulma-clean-theme
remote_theme: brooks-anderson/just-the-docs
# theme: just-the-docs
plugins:
  - jekyll-feed
  - jemoji

search_enabled: true
aux_links:
  '<i class="fa fa-github fa-2x"></i>':
    - "//github.com/brooks-anderson"
  '<i class="fa fa-linkedin fa-2x"></i>':
    - "//linkedin.com/in/brooks-s-anderson"

nav_external_links:
  - title: Home
    url: https://brooks-anderson.github.io
    hide_icon: true # set to true to hide the external link icon - defaults to false
  - title: Projects
    url: https://brooks-anderson.github.io/projects
    hide_icon: true
